### ISSUE TITLE
wiki not in english

### ISSUE THREAD

**Issue by rockocoop** [berkiadam/haproxy-metrics#2]
What you have done here looks very interesting.  Any chance you have a version of the wiki in english?

**Comment by berkiadam** [comment]
Hi Rockocoop,
I will translate it soon, not a big deal. Please come back in a week. I always wanted to translate my wiki anyway

**Comment by berkiadam** [comment]
Translation is done.

**Comment by rockocoop** [comment]
Very cool. Looks good. Ill try it out!

בתאריך יום א׳, 24 בנוב׳ 2019, 22:56, מאת Adam Berki ‏<
notifications@github.com>:

**Comment by rockocoop** [comment]
By the way, any thoughts on integrating it with splunk?

בתאריך יום ב׳, 25 בנוב׳ 2019, 12:27, מאת טינו קלמנטינו ‏<rockocoop@gmail.com
