### ISSUE TITLE
tried it in OCP 3.11

### ISSUE THREAD

**Issue by rockocoop** [berkiadam/haproxy-metrics#3]
didnt see the router in targets page in prometheus

**Comment by berkiadam** [comment]
Could you send me your Prometheus config file?  You can check if Prometheus is able to read from the Kubernetes API to query the list of target objects. You should also check the start of logs of Prometheus with the kubectl logs <pod-name> -c prometheus-server command. You can send me the logs as well.

**Comment by rockocoop** [comment]
i added a servicemonitor in the openshift-monitoring project and now i see them
